name: Test PR

on:
  push:

jobs:
  test:
    name: Test PR
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: src

    - run: sudo ln -s "$(which gfortran-11)" /usr/local/bin/gfortran
    - run: make -C src -j3 DESTDIR="$(pwd)/julia" prefix= VERBOSE=1 install
    - run: src/mac_embedding_test/test.sh julia
